[2017-11-02 16:10:23] INFO - FastDFS v5.05, base_path=./fastdfs/client, run_by_group=, run_by_user=, connect_timeout=30s, network_timeout=60s, port=22000, bind_addr=, max_connections=256, accept_threads=1, work_threads=4, store_lookup=0, store_group=, store_server=0, store_path=0, reserved_storage_space=1024 MB, download_server=0, allow_ip_count=-1, sync_log_buff_interval=10s, check_active_interval=100s, thread_stack_size=64 KB, storage_ip_changed_auto_adjust=1, storage_sync_file_max_delay=86400s, storage_sync_file_max_time=300s, use_trunk_file=0, slot_min_size=256, slot_max_size=32 MB, trunk_file_size=64 MB, trunk_create_file_advance=0, trunk_create_file_time_base=02:00, trunk_create_file_interval=86400, trunk_create_file_space_threshold=0 GB, trunk_init_check_occupying=0, trunk_init_reload_from_binlog=0, trunk_compress_binlog_min_interval=0, use_storage_id=0, id_type_in_filename=ip, storage_id_count=0, rotate_error_log=0, error_log_rotate_time=00:00, rotate_error_log_size=0, log_file_keep_days=0, store_slave_file_use_link=0, use_connection_pool=0, g_connection_pool_max_idle_time=3600s
[2017-11-02 16:10:23] INFO - local_host_ip_count: 4,  127.0.0.1  10.44.58.172  101.200.170.171  192.168.0.1
[2017-11-02 16:10:23] ERROR - file: shared_func.c, line: 1085, open file ./fastdfs/client/data/fdfs_trackerd.pid fail, errno: 2, error info: No such file or directory
